# 免费邮箱API
mail:
  api: API

# 请求
requests:
  # 超时设置
  out_time: 120
  # 重试次数
  retry: 10

pikpak_user:
 - mail: wiwaret166@talmetry.com
   pd: 098poi
   invite_number: 95370395
   share:
     - "JAV_output_temp"
 - mail: lopipi9801@giratex.com
   pd: 098poi
   invite_number: 39576161
   share:
     - "sehuatang_temp"
     - "JAV_output"
 - mail: weyel44478@namewok.com
   pd: 098poi
   invite_number: 92196679
   share:
     - "影视"
 - mail: himiren433@picvw.com
   pd: poi098
   invite_number: 85147854
   share:
     - "整理"
  - mail: vepahe1532@roborena.com
    pd: 098poi
    invite_number: 74553676
    share:
      - "SukebeiEnyo合集一"
  - mail: hamidan206@otemdi.com
    pd: 098poi
    invite_number: 74925778
    share:
      - "upload"
      - "动漫"
      - "写真"
      - "未整理"
      - "欧美"
      - "中国"
      - "整理"
      - "直播"